[package]
name = "capefox"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
reqwest = { version = "0.12.5", features = ["json"] }
serde_json = "1.0.117"
serde_json_path = "0.6.7"
tokio = { version = "1.38.0", features = ["full"]}
